Use proper cloning and updating commands

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -89,7 +89,7 @@ runs:
 
         if [[ ${{ inputs.add_repos }} == true ]]; then
           # Committing is necessary if we want to revert the changes and fetching
-          # the script at the same time, as otherwise, the script below would fail.
+          # the script at the same time, as otherwise, the scriptS below would fail.
           if [[ ! -f fetch-repos.lua ]]; then
             wget https://raw.githubusercontent.com/Panquesito7/submodules-alternative/main/fetch-repos.lua
             git add fetch-repos.lua
@@ -100,13 +100,15 @@ runs:
         if [[ ${{ inputs.update_repos }} == true ]]; then
           if [[ ! -f update-repos.lua ]]; then
             wget https://raw.githubusercontent.com/Panquesito7/submodules-alternative/main/update-repos.lua
+            git add update-repos.lua
+            git commit -m "Get the update-repos script"
           fi
         fi
     - name: Clone repositories
       shell: bash
       run: |
         if [[ ${{ inputs.add_repos }} == true ]]; then
-          lua fetch-repos.lua ${{ inputs.repos_filename }} ${{ inputs.squash_commits }}
+          lua fetch-repos.lua ${{ inputs.repos_filename }} ${{ inputs.squash_commits }} ${{ inputs.commit_message }}
         fi
     - name: Update repositories
       shell: bash
@@ -120,6 +122,11 @@ runs:
         # Removes the `fetch-repos.lua` script from the repository, as it is not needed.
         if [[ ${{ inputs.add_repos }} == true ]]; then
           git revert $(git log --branches --not --remotes --grep 'Get the fetch-repos script' --oneline | cut -d' ' -f1) --no-edit || true
+        fi
+
+        # Removes the `update-repos.lua` script from the repository, as it is not needed.
+        if [[ ${{ inputs.update_repos }} == true ]]; then
+          git revert $(git log --branches --not --remotes --grep 'Get the update-repos script' --oneline | cut -d' ' -f1) --no-edit || true
         fi
 
         if [[ ${{ inputs.use_pr }} == true ]]; then
